
name: Reusable workflow
on:
  workflow_call:
    # inputs:
    #   username:
    #     required: true
    #     type: string
    # secrets:
    #   envPAT:
    #     required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Reusable workflow job

# jobs:
#   reusable_workflow_job:
#     runs-on: ubuntu-latest
#     environment: production
#     steps:
#       - uses: ./.github/actions/my-action
#         with:
#           username: ${{ inputs.username }}
#           token: ${{ secrets.envPAT }}